services:
  - type: web
    name: orial-backend
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node server.js
   
    plan: free
    rootDir: backend
